### ISSUE TITLE
Modifications sur le site

### ISSUE THREAD

**Issue by lgf-dti** [Dovhachero-Brocko-Fenryrson/SiteGIT#2]
Voici les modifications pour le site :

- [x] Ajouter une entrée dans le menu avec le lien vers le dépot Github (pas sur le site)

- [x] Ajouter les sites (sources) pour la partie "A quoi sert GIT"

Merci !

**Comment by Dovhachero-Brocko-Fenryrson** [comment]
toute les modification on été faite
